var moves = [
    {"name":"Acid", "type":"poison", "pokemons":["arbok", "ekans", "oddish", "gloom", "vileplume","bellspout","weepinbell","victreebel","tendacruel","grimmer","muk","koffing", "weezing"]},
    {"name":"Bite", "type":"dark", "pokemons":[]},
    {"name":"Bubble", "type":"water", "pokemons":[]},
    {"name":"Bug Bite", "type":"bug", "pokemons":[]},
    {"name":"Bullet Punch", "type":"steel", "pokemons":[]},
    {"name":"Confusion", "type":"psychic", "pokemons":[]},
    {"name":"Cut","type":"normal", "pokemons":[]},
    {"name":"Dragon Breath","type":"dragon", "pokemons":[]},
    {"name":"Ember","type":"fire", "pokemons":[]},
    {"name":"Feint Attack","type":"dark", "pokemons":[]},
    {"name":"Fire Fang","type":"fire", "pokemons":[]},
    {"name":"Frost Breath","type":"ice", "pokemons":[]},
    {"name":"Fury Cutter","type":"bug", "pokemons":[]},
    {"name":"Ice Shard","type":"ice", "pokemons":[]},
    {"name":"Karate Chop","type":"fight", "pokemons":[]},
    {"name":"Lick","type":"ghost", "pokemons":[]},
    {"name":"Low Kick","type":"fight", "pokemons":[]},
    {"name":"Metal Claw","type":"steel", "pokemons":[]},
    {"name":"Mud Shot","type":"ground", "pokemons":[]},
    {"name":"Mud Slap","type":"ground", "pokemons":[]},
    {"name":"Peck","type":"flying", "pokemons":[]},
    {"name":"Poison Jab","type":"poison", "pokemons":[]},
    {"name":"Poison Sting","type":"poison", "pokemons":[]},
    {"name":"Pound","type":"normal", "pokemons":[]},
    {"name":"Psycho Cut","type":"psychic", "pokemons":[]},
    {"name":"Quick Attack","type":"normal", "pokemons":[]},
    {"name":"Razor Leaf","type":"grass", "pokemons":[]},
    {"name":"Rock Smash","type":"fight", "pokemons":[]},
    {"name":"Rock Throw","type":"rock", "pokemons":[]},
    {"name":"Scratch","type":"normal", "pokemons":[]},
    {"name":"Shadow Claw","type":"ghost", "pokemons":[]},
    {"name":"Spark","type":"electric", "pokemons":[]},
    {"name":"Splash","type":"water", "pokemons":[]},
    {"name":"Steel Wing","type":"steel", "pokemons":[]},
    {"name":"Sucker Punch","type":"dark", "pokemons":[]},
    {"name":"Tackle","type":"normal", "pokemons":[]},
    {"name":"Thunder Shock","type":"electric", "pokemons":[]},
    {"name":"Vine Whip","type":"grass", "pokemons":[]},
    {"name":"Water Gun","type":"water", "pokemons":[]},
    {"name":"Wing Attack","type":"flying", "pokemons":[]},
    {"name":"Zen Headbutt","type":"psychic", "pokemons":[]}
];
